[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/quote"
  to = "https://random-quote.hyobb.com"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200